#!/bin/bash
if [ "$#" -ne 1 ]; then
    echo "Invalid number of arguments"
    echo "./runall <spec2017_dir>"
    exit
fi

if [ ! -d "$1" ] || [ ! -f "$1/shrc" ]; then
    echo "Invalid spec2017 directory"
    echo "It needs to be the directory with 'shrc' file inside"
fi

CURRENT_PATH=$(pwd)

PROGRAMS=(
  500.perlbench_r
  502.gcc_r
  505.mcf_r
  520.omnetpp_r
  523.xalancbmk_r
  525.x264_r
  531.deepsjeng_r
  541.leela_r
  557.xz_r
  999.specrand_ir
)

for i in {0..9}; do
    PROGRAM="${PROGRAMS[$i]}"
    PROGPATH="${1}/benchspec/CPU/${PROGRAM}/run/run_base_refrate_mytest-m64.0000"
    
    cp run $PROGPATH
    cp setup $PROGPATH
    cp wrapper.template $PROGPATH
    
    cd $PROGPATH
    echo $i | ./setup
    screen -dmS $PROGRAM ./run
done
